import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Share, Alert } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { COLORS, SPACING, RADIUS, FONT, SHADOW } from '../theme';

export default function DietPlanDetailScreen({ route, navigation }) {
    const { plan } = route.params;
    const insets = useSafeAreaInsets();

    const handleShare = async () => {
        try {
            let text = `📋 ${plan.title}\n${plan.desc}\n\n`;
            text += `🗓️ Duration: ${plan.duration}\n🔥 Daily Calories: ${plan.totalCalories} kcal\n\n`;
            text += `--- MEAL PLAN ---\n\n`;
            plan.meals.forEach(m => {
                text += `🍽️ ${m.meal} (${m.calories} kcal)\n`;
                m.items.forEach(item => { text += `  • ${item}\n`; });
                text += `\n`;
            });
            text += `--- TIPS ---\n`;
            plan.tips.forEach(tip => { text += `💡 ${tip}\n`; });
            text += `\nShared from VitalIQ 🍃`;

            await Share.share({ message: text, title: plan.title });
        } catch (error) {
            Alert.alert('Error', 'Could not share diet plan.');
        }
    };

    const generatePlanText = () => {
        let text = `=== ${plan.title} ===\n${plan.desc}\n\n`;
        text += `Duration: ${plan.duration}\nDaily Calories: ${plan.totalCalories} kcal\n\n`;
        text += `--- DAILY MEAL PLAN ---\n\n`;
        plan.meals.forEach(m => {
            text += `${m.meal} (${m.calories} kcal)\n`;
            m.items.forEach(item => { text += `  • ${item}\n`; });
            text += `\n`;
        });
        text += `--- TIPS & GUIDELINES ---\n`;
        plan.tips.forEach(tip => { text += `• ${tip}\n`; });
        text += `\n--- Generated by VitalIQ ---\n`;
        return text;
    };

    const handleDownload = async () => {
        try {
            const fileName = plan.title.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
            const pdfName = `${fileName}.pdf`;
            // Using your laptop's local IP for network accessibility
            const pdfUrl = `http://192.168.1.11:5000/diet-pdfs/${pdfName}`;
            const fileUri = FileSystem.documentDirectory + pdfName;

            console.log(`[Diet] Downloading PDF from: ${pdfUrl}`);
            
            const downloadRes = await FileSystem.downloadAsync(pdfUrl, fileUri);

            if (downloadRes.status !== 200) {
                throw new Error('PDF not found on server');
            }

            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(fileUri, {
                    mimeType: 'application/pdf',
                    dialogTitle: `Download ${plan.title}`,
                });
            } else {
                Alert.alert('Saved!', `Diet plan saved to: ${fileUri}`);
            }
        } catch (error) {
            console.error('Download error:', error);
            Alert.alert('Error', 'Could not download the official PDF plan. Falling back to sharing text summary...');
            handleShare();
        }
    };

    return (
        <View style={[styles.container, { paddingTop: insets.top }]}>
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
                    <Text style={styles.backText}>← Back</Text>
                </TouchableOpacity>
                <TouchableOpacity onPress={handleShare}>
                    <Text style={styles.shareText}>Share 📤</Text>
                </TouchableOpacity>
            </View>

            <ScrollView contentContainerStyle={styles.inner} showsVerticalScrollIndicator={false}>
                {/* Title Section */}
                <View style={styles.titleSection}>
                    <View style={styles.iconBox}>
                        <Text style={styles.icon}>{plan.icon}</Text>
                    </View>
                    <Text style={styles.title}>{plan.title}</Text>
                    <Text style={styles.desc}>{plan.desc}</Text>

                    <View style={styles.metaRow}>
                        <View style={styles.metaChip}>
                            <Text style={styles.metaLabel}>📅 {plan.duration}</Text>
                        </View>
                        <View style={styles.metaChip}>
                            <Text style={styles.metaLabel}>🔥 {plan.totalCalories} kcal/day</Text>
                        </View>
                        <View style={styles.metaChip}>
                            <Text style={styles.metaLabel}>📂 {plan.category}</Text>
                        </View>
                    </View>
                </View>

                {/* Meals */}
                <Text style={styles.sectionTitle}>Daily Meal Plan</Text>
                {plan.meals.map((meal, index) => (
                    <View key={index} style={styles.mealCard}>
                        <View style={styles.mealHeader}>
                            <Text style={styles.mealName}>{meal.meal}</Text>
                            <Text style={styles.mealCal}>{meal.calories} kcal</Text>
                        </View>
                        {meal.items.map((item, i) => (
                            <View key={i} style={styles.mealItemRow}>
                                <Text style={styles.bullet}>•</Text>
                                <Text style={styles.mealItem}>{item}</Text>
                            </View>
                        ))}
                    </View>
                ))}

                {/* Tips */}
                <Text style={styles.sectionTitle}>Tips & Guidelines</Text>
                <View style={styles.tipsCard}>
                    {plan.tips.map((tip, i) => (
                        <View key={i} style={styles.tipRow}>
                            <Text style={styles.tipIcon}>💡</Text>
                            <Text style={styles.tipText}>{tip}</Text>
                        </View>
                    ))}
                </View>

                {/* Summary */}
                <View style={styles.summaryCard}>
                    <Text style={styles.summaryTitle}>Daily Nutrition Summary</Text>
                    <View style={styles.summaryRow}>
                        <Text style={styles.summaryLabel}>Total Calories</Text>
                        <Text style={styles.summaryValue}>{plan.totalCalories} kcal</Text>
                    </View>
                    <View style={styles.summaryRow}>
                        <Text style={styles.summaryLabel}>Meals per Day</Text>
                        <Text style={styles.summaryValue}>{plan.meals.length}</Text>
                    </View>
                    <View style={styles.summaryRow}>
                        <Text style={styles.summaryLabel}>Plan Duration</Text>
                        <Text style={styles.summaryValue}>{plan.duration}</Text>
                    </View>
                </View>

                {/* Action buttons */}
                <TouchableOpacity style={styles.shareBtn} onPress={handleDownload}>
                    <Text style={styles.shareBtnIcon}>📥</Text>
                    <Text style={styles.shareBtnText}>Download Plan</Text>
                </TouchableOpacity>

                <TouchableOpacity style={[styles.shareBtn, styles.secondaryBtn]} onPress={handleShare}>
                    <Text style={styles.shareBtnIcon}>📤</Text>
                    <Text style={[styles.shareBtnText, { color: COLORS.primary }]}>Share This Plan</Text>
                </TouchableOpacity>

                <View style={{ height: 40 }} />
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    header: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        paddingHorizontal: SPACING.xl, paddingVertical: SPACING.md,
    },
    backBtn: { padding: SPACING.xs },
    backText: { color: COLORS.primary, fontSize: FONT.md, fontWeight: FONT.bold },
    shareText: { color: COLORS.textSecondary, fontSize: FONT.sm, fontWeight: FONT.medium },
    inner: { padding: SPACING.xl },

    titleSection: { alignItems: 'center', marginBottom: SPACING.xxl },
    iconBox: {
        backgroundColor: COLORS.primaryLight, width: 80, height: 80,
        borderRadius: RADIUS.xl, justifyContent: 'center', alignItems: 'center', marginBottom: SPACING.lg,
    },
    icon: { fontSize: 40 },
    title: { fontSize: FONT.xxl, fontWeight: FONT.black, color: COLORS.text, textAlign: 'center', marginBottom: SPACING.sm },
    desc: { fontSize: FONT.md, color: COLORS.textSecondary, textAlign: 'center', paddingHorizontal: SPACING.xl, lineHeight: 22 },
    metaRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', marginTop: SPACING.lg },
    metaChip: {
        backgroundColor: COLORS.surface, paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm, borderRadius: RADIUS.pill, marginHorizontal: SPACING.xs, marginBottom: SPACING.xs,
        borderWidth: 1, borderColor: COLORS.border,
    },
    metaLabel: { color: COLORS.textSecondary, fontSize: FONT.xs, fontWeight: FONT.medium },

    sectionTitle: { color: COLORS.text, fontSize: FONT.lg, fontWeight: FONT.bold, marginBottom: SPACING.md, marginTop: SPACING.sm },

    mealCard: {
        backgroundColor: COLORS.surface, padding: SPACING.lg, borderRadius: RADIUS.lg,
        marginBottom: SPACING.md, borderWidth: 1, borderColor: COLORS.border,
    },
    mealHeader: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        marginBottom: SPACING.md, paddingBottom: SPACING.sm, borderBottomWidth: 1, borderBottomColor: COLORS.border,
    },
    mealName: { color: COLORS.text, fontSize: FONT.md, fontWeight: FONT.semibold },
    mealCal: { color: COLORS.primary, fontSize: FONT.sm, fontWeight: FONT.bold },
    mealItemRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: SPACING.xs },
    bullet: { color: COLORS.textSecondary, fontSize: FONT.md, marginRight: SPACING.sm, lineHeight: 20 },
    mealItem: { color: COLORS.textSecondary, fontSize: FONT.sm, lineHeight: 20, flex: 1 },

    tipsCard: {
        backgroundColor: COLORS.primaryLight, padding: SPACING.lg, borderRadius: RADIUS.lg,
        marginBottom: SPACING.xl,
    },
    tipRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: SPACING.md },
    tipIcon: { fontSize: 14, marginRight: SPACING.sm, marginTop: 2 },
    tipText: { color: COLORS.text, fontSize: FONT.sm, lineHeight: 20, flex: 1 },

    summaryCard: {
        backgroundColor: COLORS.surface, padding: SPACING.xl, borderRadius: RADIUS.xl,
        marginBottom: SPACING.xl, borderWidth: 1, borderColor: COLORS.border,
    },
    summaryTitle: { color: COLORS.primary, fontSize: FONT.sm, fontWeight: FONT.bold, textTransform: 'uppercase', letterSpacing: 1, marginBottom: SPACING.md },
    summaryRow: {
        flexDirection: 'row', justifyContent: 'space-between', paddingVertical: SPACING.md,
        borderBottomWidth: 1, borderBottomColor: COLORS.border,
    },
    summaryLabel: { color: COLORS.textSecondary, fontSize: FONT.md },
    summaryValue: { color: COLORS.text, fontSize: FONT.md, fontWeight: FONT.semibold },

    shareBtn: {
        backgroundColor: COLORS.primary, flexDirection: 'row', width: '100%',
        padding: SPACING.lg, borderRadius: RADIUS.lg, alignItems: 'center', justifyContent: 'center',
        ...SHADOW.md,
    },
    shareBtnIcon: { fontSize: 18, marginRight: SPACING.sm },
    shareBtnText: { color: COLORS.textInverse, fontSize: FONT.lg, fontWeight: FONT.bold },
    secondaryBtn: {
        backgroundColor: 'transparent', borderWidth: 1, borderColor: COLORS.primary,
        marginTop: SPACING.md,
    },
});
