import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Share, Alert } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { useTheme } from '../context/ThemeContext';
import { SPACING, RADIUS, FONT, SHADOW } from '../theme';

export default function DietPlanDetailScreen({ route, navigation }) {
    const { plan } = route.params || {};
    const insets = useSafeAreaInsets();
    const { theme } = useTheme();

    // Null-guard: prevent crash if plan is missing
    if (!plan) {
        return (
            <View style={{ flex: 1, backgroundColor: theme.bg, justifyContent: 'center', alignItems: 'center' }}>
                <Text style={{ color: theme.danger, fontSize: 40, marginBottom: 16 }}>⚠️</Text>
                <Text style={{ color: theme.text, fontSize: 16 }}>No plan data available.</Text>
            </View>
        );
    }

    const generatePlanText = () => {
        let text = `=== ${plan.title} ===\n${plan.desc}\n\n`;
        text += `Duration: ${plan.duration}\nDaily Calories: ${plan.totalCalories} kcal\n\n`;
        text += `--- DAILY MEAL PLAN ---\n\n`;
        (plan.meals || []).forEach(m => {
            text += `${m.meal} (${m.calories} kcal)\n`;
            (m.items || []).forEach(item => { text += `  • ${item}\n`; });
            text += `\n`;
        });
        text += `--- TIPS & GUIDELINES ---\n`;
        (plan.tips || []).forEach(tip => { text += `• ${tip}\n`; });
        text += `\n--- Generated by VitalIQ ---\n`;
        return text;
    };

    const handleShare = async () => {
        try {
            let text = `📋 ${plan.title}\n${plan.desc}\n\n`;
            text += `🗓️ Duration: ${plan.duration}\n🔥 Daily Calories: ${plan.totalCalories} kcal\n\n`;
            text += `--- MEAL PLAN ---\n\n`;
            (plan.meals || []).forEach(m => {
                text += `🍽️ ${m.meal} (${m.calories} kcal)\n`;
                (m.items || []).forEach(item => { text += `  • ${item}\n`; });
                text += `\n`;
            });
            text += `--- TIPS ---\n`;
            (plan.tips || []).forEach(tip => { text += `💡 ${tip}\n`; });
            text += `\nShared from VitalIQ 🍃`;
            await Share.share({ message: text, title: plan.title });
        } catch (error) {
            Alert.alert('Error', 'Could not share diet plan.');
        }
    };

    // ✅ FIXED: Local text-file export — no server needed, works on real device
    const handleDownload = async () => {
        try {
            const safeName = (plan.title || 'diet').replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
            const fileUri = `${FileSystem.documentDirectory}${safeName}_plan.txt`;
            const content = generatePlanText();

            await FileSystem.writeAsStringAsync(fileUri, content, {
                encoding: FileSystem.EncodingType.UTF8,
            });

            Alert.alert('Downloaded successfully', `Plan saved to device storage:\n${fileUri}`);

            const isAvailable = await Sharing.isAvailableAsync();
            if (isAvailable) {
                await Sharing.shareAsync(fileUri, {
                    mimeType: 'text/plain',
                    dialogTitle: `Save ${plan.title}`,
                    UTI: 'public.plain-text',
                });
            } else {
                Alert.alert('Saved!', `Plan saved to:\n${fileUri}`);
            }
        } catch (error) {
            console.error('[Diet Download]', error);
            Alert.alert('Error', 'Could not save the diet plan. Please try sharing instead.');
        }
    };

    return (
        <View style={[styles.container, { paddingTop: insets.top, backgroundColor: theme.bg }]}>
            {/* Header */}
            <View style={[styles.header, { borderBottomColor: theme.border }]}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
                    <Text style={[styles.backText, { color: theme.primary }]}>← Back</Text>
                </TouchableOpacity>
                <TouchableOpacity onPress={handleShare}>
                    <Text style={[styles.shareText, { color: theme.textSecondary }]}>Share 📤</Text>
                </TouchableOpacity>
            </View>

            <ScrollView contentContainerStyle={styles.inner} showsVerticalScrollIndicator={false}>
                {/* Title Section */}
                <View style={styles.titleSection}>
                    <View style={[styles.iconBox, { backgroundColor: theme.primaryLight }]}>
                        <Text style={styles.icon}>{plan.icon}</Text>
                    </View>
                    <Text style={[styles.title, { color: theme.text }]}>{plan.title}</Text>
                    <Text style={[styles.desc, { color: theme.textSecondary }]}>{plan.desc}</Text>

                    <View style={styles.metaRow}>
                        <View style={[styles.metaChip, { backgroundColor: theme.surface, borderColor: theme.border }]}>
                            <Text style={[styles.metaLabel, { color: theme.textSecondary }]}>📅 {plan.duration}</Text>
                        </View>
                        <View style={[styles.metaChip, { backgroundColor: theme.surface, borderColor: theme.border }]}>
                            <Text style={[styles.metaLabel, { color: theme.textSecondary }]}>🔥 {plan.totalCalories} kcal/day</Text>
                        </View>
                        <View style={[styles.metaChip, { backgroundColor: theme.surface, borderColor: theme.border }]}>
                            <Text style={[styles.metaLabel, { color: theme.textSecondary }]}>📂 {plan.category}</Text>
                        </View>
                    </View>
                </View>

                {/* Meals */}
                <Text style={[styles.sectionTitle, { color: theme.text }]}>Daily Meal Plan</Text>
                {(plan.meals || []).map((meal, index) => (
                    <View key={index} style={[styles.mealCard, { backgroundColor: theme.surface, borderColor: theme.border }]}>
                        <View style={[styles.mealHeader, { borderBottomColor: theme.border }]}>
                            <Text style={[styles.mealName, { color: theme.text }]}>{meal.meal}</Text>
                            <Text style={[styles.mealCal, { color: theme.primary }]}>{meal.calories} kcal</Text>
                        </View>
                        {(meal.items || []).map((item, i) => (
                            <View key={i} style={styles.mealItemRow}>
                                <Text style={[styles.bullet, { color: theme.textSecondary }]}>•</Text>
                                <Text style={[styles.mealItem, { color: theme.textSecondary }]}>{item}</Text>
                            </View>
                        ))}
                    </View>
                ))}

                {/* Tips */}
                <Text style={[styles.sectionTitle, { color: theme.text }]}>Tips & Guidelines</Text>
                <View style={[styles.tipsCard, { backgroundColor: theme.primaryLight }]}>
                    {(plan.tips || []).map((tip, i) => (
                        <View key={i} style={styles.tipRow}>
                            <Text style={styles.tipIcon}>💡</Text>
                            <Text style={[styles.tipText, { color: theme.text }]}>{tip}</Text>
                        </View>
                    ))}
                </View>

                {/* Summary */}
                <View style={[styles.summaryCard, { backgroundColor: theme.surface, borderColor: theme.border }]}>
                    <Text style={[styles.summaryTitle, { color: theme.primary }]}>Daily Nutrition Summary</Text>
                    <View style={[styles.summaryRow, { borderBottomColor: theme.border }]}>
                        <Text style={[styles.summaryLabel, { color: theme.textSecondary }]}>Total Calories</Text>
                        <Text style={[styles.summaryValue, { color: theme.text }]}>{plan.totalCalories} kcal</Text>
                    </View>
                    <View style={[styles.summaryRow, { borderBottomColor: theme.border }]}>
                        <Text style={[styles.summaryLabel, { color: theme.textSecondary }]}>Meals per Day</Text>
                        <Text style={[styles.summaryValue, { color: theme.text }]}>{(plan.meals || []).length}</Text>
                    </View>
                    <View style={[styles.summaryRow, { borderBottomColor: theme.border }]}>
                        <Text style={[styles.summaryLabel, { color: theme.textSecondary }]}>Plan Duration</Text>
                        <Text style={[styles.summaryValue, { color: theme.text }]}>{plan.duration}</Text>
                    </View>
                </View>

                {/* Action buttons */}
                <TouchableOpacity
                    style={[styles.actionBtn, { backgroundColor: theme.primary }]}
                    onPress={handleDownload}
                >
                    <Text style={styles.actionBtnIcon}>📥</Text>
                    <Text style={[styles.actionBtnText, { color: '#fff' }]}>Download Plan (.txt)</Text>
                </TouchableOpacity>

                <TouchableOpacity
                    style={[styles.actionBtn, styles.secondaryBtn, { borderColor: theme.primary }]}
                    onPress={handleShare}
                >
                    <Text style={styles.actionBtnIcon}>📤</Text>
                    <Text style={[styles.actionBtnText, { color: theme.primary }]}>Share This Plan</Text>
                </TouchableOpacity>

                <View style={{ height: 40 }} />
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1 },
    header: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        paddingHorizontal: SPACING.xl, paddingVertical: SPACING.md,
        borderBottomWidth: 1,
    },
    backBtn: { padding: SPACING.xs },
    backText: { fontSize: FONT.md, fontWeight: FONT.bold },
    shareText: { fontSize: FONT.sm, fontWeight: FONT.medium },
    inner: { padding: SPACING.xl },

    titleSection: { alignItems: 'center', marginBottom: SPACING.xxl },
    iconBox: {
        width: 80, height: 80,
        borderRadius: RADIUS.xl, justifyContent: 'center', alignItems: 'center', marginBottom: SPACING.lg,
    },
    icon: { fontSize: 40 },
    title: { fontSize: FONT.xxl, fontWeight: FONT.black, textAlign: 'center', marginBottom: SPACING.sm },
    desc: { fontSize: FONT.md, textAlign: 'center', paddingHorizontal: SPACING.xl, lineHeight: 22 },
    metaRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', marginTop: SPACING.lg },
    metaChip: {
        paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm,
        borderRadius: RADIUS.pill, marginHorizontal: SPACING.xs, marginBottom: SPACING.xs,
        borderWidth: 1,
    },
    metaLabel: { fontSize: FONT.xs, fontWeight: FONT.medium },

    sectionTitle: { fontSize: FONT.lg, fontWeight: FONT.bold, marginBottom: SPACING.md, marginTop: SPACING.sm },

    mealCard: {
        padding: SPACING.lg, borderRadius: RADIUS.lg,
        marginBottom: SPACING.md, borderWidth: 1,
    },
    mealHeader: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        marginBottom: SPACING.md, paddingBottom: SPACING.sm, borderBottomWidth: 1,
    },
    mealName: { fontSize: FONT.md, fontWeight: FONT.semibold },
    mealCal: { fontSize: FONT.sm, fontWeight: FONT.bold },
    mealItemRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: SPACING.xs },
    bullet: { fontSize: FONT.md, marginRight: SPACING.sm, lineHeight: 20 },
    mealItem: { fontSize: FONT.sm, lineHeight: 20, flex: 1 },

    tipsCard: { padding: SPACING.lg, borderRadius: RADIUS.lg, marginBottom: SPACING.xl },
    tipRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: SPACING.md },
    tipIcon: { fontSize: 14, marginRight: SPACING.sm, marginTop: 2 },
    tipText: { fontSize: FONT.sm, lineHeight: 20, flex: 1 },

    summaryCard: {
        padding: SPACING.xl, borderRadius: RADIUS.xl,
        marginBottom: SPACING.xl, borderWidth: 1,
    },
    summaryTitle: { fontSize: FONT.sm, fontWeight: FONT.bold, textTransform: 'uppercase', letterSpacing: 1, marginBottom: SPACING.md },
    summaryRow: {
        flexDirection: 'row', justifyContent: 'space-between', paddingVertical: SPACING.md,
        borderBottomWidth: 1,
    },
    summaryLabel: { fontSize: FONT.md },
    summaryValue: { fontSize: FONT.md, fontWeight: FONT.semibold },

    actionBtn: {
        flexDirection: 'row', width: '100%',
        padding: SPACING.lg, borderRadius: RADIUS.lg,
        alignItems: 'center', justifyContent: 'center',
        borderRadius: 12, ...SHADOW.md,
    },
    actionBtnIcon: { fontSize: 18, marginRight: SPACING.sm },
    actionBtnText: { fontSize: FONT.lg, fontWeight: FONT.bold },
    secondaryBtn: {
        backgroundColor: 'transparent', borderWidth: 1.5,
        marginTop: SPACING.md,
    },
});
